logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    cn.blbsz.wechat: DEBUG

wechat:
  mp:
    appId: wx4503c74a0a11f606
    secret: 38f7b77476989f28f8c06015464cd2b2
#    appId: wx775d484a3fb00308
#    secret: 249ff67afc47be12f4c4b682cfb7f409
    token: weixin
    aesKey: y1ibMW8Px0znvNoikCwxOsQmBDOjFqD8KJ0nqhI7zkO

server:
  port: 80
  address:
spring:
  datasource:
#    url: jdbc:log4jdbc:sqlserver://106.15.43.125:1433;DatabaseName=winmob3
    url: jdbc:log4jdbc:mysql:///wechat_shop?createDatabaseIfNotExist=true&amp;user=root&amp;password=&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: root
#    password: Yi2017Dat@
    driver-class-name: net.sf.log4jdbc.DriverSpy
    tomcat:
      initial-size: 1
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
     hibernate:
        ddl-auto: update
        naming:
#          strategy: org.hibernate.cfg.ImprovedNamingStrategy
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     show-sql: true
     properties:
        hibernate.format_sql: true
#        hibernate.dialect: cn.blbsz.dialect.MySQLServerDialect
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     database: sql_server
#     database-platform: SQL_SERVER

  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html


